export const LAUNCHES_REQUEST='LAUNCHES_REQUEST';
export const LAUNCHES_SUCCESS='LAUNCHES_SUCCESS';
export const LAUNCHES_FAIL='LAUNCHES_FAIL';

export const LAUNCH_DETAIL_REQUEST='LAUNCH_DETAIL_REQUEST';
export const LAUNCH_DETAIL_SUCCESS='LAUNCH_DETAIL_SUCCESS';
export const LAUNCH_DETAIL_FAIL='LAUNCH_DETAIL_FAIL';

export const LAUNCH_UPCOMING_REQUEST='LAUNCH_UPCOMING_REQUEST';
export const LAUNCH_UPCOMING_SUCCESS='LAUNCH_UPCOMING_SUCCESS';
export const LAUNCH_UPCOMING_FAIL='LAUNCH_UPCOMING_FAIL';

export const LAUNCH_PAST_REQUEST='LAUNCH_PAST_REQUEST';
export const LAUNCH_PAST_SUCCESS='LAUNCH_PAST_SUCCESS';
export const LAUNCH_PAST_FAIL='LAUNCH_PAST_FAIL';